name: mar6-2
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: mar6-2
  id: 6fa231b4-9a55-4976-bd8b-d11cb5e1f1b1
events:
  post-db-import:
    - appserver: cd $LANDO_MOUNT && composer install
services:
  appserver:
    overrides:
      services:
        environment:
          BEHAT_PARAMS: >-
            {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
            "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
            "root":  "/app/web" }}}}
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
